/*

 CAFE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : robotcafe - other tiles ver2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __cafe_map_h_INCLUDE
#define __cafe_map_h_INCLUDE

#define cafe_mapWidth 20
#define cafe_mapHeight 18
#define cafe_mapBank 0

#define cafe_map cafe_mapPLN0
extern const unsigned char cafe_mapPLN0[];

#endif

/* End of CAFE_MAP.H */
