/*

 TEXTBOX_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : Z:\Users\gambero\repos\robotcafe\res\robotcafe - text box.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 304
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __textbox_map_h_INCLUDE
#define __textbox_map_h_INCLUDE

#define textbox_mapWidth 20
#define textbox_mapHeight 6
#define textbox_mapBank 0

#define textbox_map textbox_mapPLN0
extern const unsigned char textbox_mapPLN0[];

#endif

/* End of TEXTBOX_MAP.H */
