//AUTOGENERATED FILE FROM png2asset
// Conversion args: /titlescreen.png -map

#ifndef METASPRITE_titlescreen_H
#define METASPRITE_titlescreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define titlescreen_TILE_ORIGIN 0
#define titlescreen_TILE_W 8
#define titlescreen_TILE_H 8
#define titlescreen_WIDTH 160
#define titlescreen_HEIGHT 144
#define titlescreen_TILE_COUNT 77
#define titlescreen_PALETTE_COUNT 1
#define titlescreen_COLORS_PER_PALETTE 4
#define titlescreen_TOTAL_COLORS 4
#define titlescreen_MAP_ATTRIBUTES 0
extern const unsigned char titlescreen_map[360];
#define titlescreen_map_attributes titlescreen_map

BANKREF_EXTERN(titlescreen)

extern const palette_color_t titlescreen_palettes[4];
extern const uint8_t titlescreen_tiles[1232];

#endif
